<a href="https://colab.research.google.com/github/NagaSaiRamu/Data-Analytics-/blob/main/dataAnalysisBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
marks=pd.Series([90,98,99,99])
print(marks)

0    90
1    98
2    99
3    99
dtype: int64

In [ ]:
data={
    'Name':['nsr','sivani','kaka','butter','pavan','manoj'],
    'Marks':[98,99,97,96,98,99]
}

df=pd.DataFrame(data)
df

     Name  Marks
0     nsr     98
1  sivani     99
2    kaka     97
3  butter     96
4   pavan     98
5   manoj     99

In [ ]:
data={
    'Name':['nsr','sivani','kaka','butter','pavan','manoj'],
    'Marks':[98,99,97,96,98,99],
    "Subject":['Maths','science','english','social','tamil','hindi'],
    'Pass':[True,True,True,True,True,True]
}
df=pd.DataFrame(data)
df

     Name  Marks  Subject  Pass
0     nsr     98    Maths  True
1  sivani     99  science  True
2    kaka     97  english  True
3  butter     96   social  True
4   pavan     98    tamil  True
5   manoj     99    hindi  True

In [ ]:
df.shape
df.size
df.ndim

2

In [ ]:
df.index
df.columns
df.axes

[RangeIndex(start=0, stop=6, step=1),
 Index(['Name', 'Marks', 'Subject', 'Pass'], dtype='object')]

In [ ]:
df.dtypes
df.values

array([['nsr', 98, 'Maths', 'yes'],
       ['sivani', 99, 'science', 'yes'],
       ['kaka', 97, 'english', 'yes'],
       ['butter', 96, 'social', 'yes'],
       ['pavan', 98, 'tamil', 'yes'],
       ['manoj', 99, 'hindi', 'yes']], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Marks    6 non-null      int64
 2   Subject  6 non-null      object
 3   Pass     6 non-null      bool
dtypes: bool(1), int64(1), object(2)
memory usage: 282.0+ bytes

In [ ]:
df.describe()

           Marks
count   6.000000
mean   97.833333
std     1.169045
min    96.000000
25%    97.250000
50%    98.000000
75%    98.750000
max    99.000000

In [ ]:
df.memory_usage()

Index      132
Name        48
Marks       48
Subject     48
Pass         6
dtype: int64

In [ ]:
df.select_dtypes(include='object')

     Name  Subject
0     nsr    Maths
1  sivani  science
2    kaka  english
3  butter   social
4   pavan    tamil
5   manoj    hindi

In [ ]:
df.select_dtypes(include='number')

   Marks
0     98
1     99
2     97
3     96
4     98
5     99

In [ ]:
df[['Marks']]

   Marks
0     98
1     99
2     97
3     96
4     98
5     99

In [ ]:
df[['Name','Marks','Pass']]

     Name  Marks  Pass
0     nsr     98  True
1  sivani     99  True
2    kaka     97  True
3  butter     96  True
4   pavan     98  True
5   manoj     99  True

In [ ]:
df.iloc[2:4]

     Name  Marks  Subject  Pass
2    kaka     97  english  True
3  butter     96   social  True

In [ ]:
df.loc[::-1]

     Name  Marks  Subject  Pass
5   manoj     99    hindi  True
4   pavan     98    tamil  True
3  butter     96   social  True
2    kaka     97  english  True
1  sivani     99  science  True
0     nsr     98    Maths  True

In [ ]:
df.iloc[2,2]

'english'