<a href="https://colab.research.google.com/github/NagaSaiRamu/Data-Analytics-/blob/main/DataPreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('StoreData.csv')

In [ ]:
df.head()

,Order Id,Customer Name,Order Date,ship date,segment,region,quantity,sales,profit,discount,product category,postal code
0,CA-001,john smith,05-01-2020,10-01-2020,Consumer,west,2,200.5,30,10%,Electronics,500084
1,CA-002,Jane Doe,07-01-2020,11-01-2020,Consumer,West,3,300,45,0.2,Furniture,500081
2,CA-001,john smith,05-01-2020,10-01-2020,Consumer,west,2,200.5,30,10%,Electronics,500084
3,CA-003,ANNA GRAY,10-01-2020,15-01-2020,Corporate,East,5,500,missing,15%,Office Supplies,500002
4,CA-004,Mark Lee,2020-01-12,,Home Office,East,1,N/A,10,5%,Furniture,500001

In [ ]:
df.shape

(31, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order Id           31 non-null     object
 1   Customer Name      31 non-null     object
 2   Order Date         31 non-null     object
 3    ship date         31 non-null     object
 4    segment           31 non-null     object
 5    region            31 non-null     object
 6    quantity          31 non-null     object
 7    sales             31 non-null     object
 8    profit            30 non-null     object
 9    discount          31 non-null     object
 10   product category  31 non-null     object
 11   postal code       31 non-null     object
dtypes: object(12)
memory usage: 3.0+ KB

In [ ]:
df.sample(5)

,Order Id,Customer Name,Order Date,ship date,segment,region,quantity,sales,profit,discount,product category,postal code
3,CA-003,ANNA GRAY,10-01-2020,15-01-2020,Corporate,East,5,500,missing,15%,Office Supplies,500002
2,CA-001,john smith,05-01-2020,10-01-2020,Consumer,west,2,200.5,30,10%,Electronics,500084
5,CA-005,mary jane,14-01-2020,17-01-2020,consumer,South,4,400.5,70,N/A,Electronics,500084A
24,CA-024,karan,01-02-2020,08-02-2020,Corporate,north,1,100,10,5%,Office Supplies,500051
14,CA-014,bhavya,23-01-2020,30-01-2020,Home Office,east,4,450,70,0.15,Office Supplies,500043

In [ ]:
df.columns=df.columns.str.strip().str.replace(" ",'_').str.title()

In [ ]:
df.sample(5)

,Order_Id,Customer_Name,Order_Date,Ship_Date,Segment,Region,Quantity,Sales,Profit,Discount,Product_Category,Postal_Code
11,CA-011,deepak,20-01-2020,25-01-2020,consumer,north,3,310,missing,10%,Electronics,500040
10,CA-010,anjali,19-01-2020,23-01-2020,corporate,west,2,280.5,60,15%,electronics,500034
30,CA-030,varun,07-02-2020,14-02-2020,Consumer,east,2,280,50,0.1,Office Supplies,500057
0,CA-001,john smith,05-01-2020,10-01-2020,Consumer,west,2,200.5,30,10%,Electronics,500084
23,CA-023,megha,31-01-2020,07-02-2020,Consumer,south,4,410,75,15%,Furniture,500050

In [ ]:
for i in df.select_dtypes(include='object').columns:
  df[i]=df[i].str.strip()

In [ ]:
print('before', len(df))
df=df.drop_duplicates()
print('after', len(df))

before 30
after 30

In [ ]:
df.head()

,Order_Id,Customer_Name,Order_Date,Ship_Date,Segment,Region,Quantity,Sales,Profit,Discount,Product_Category,Postal_Code
0,CA-001,john smith,05-01-2020,10-01-2020,Consumer,west,2,200.5,30,10%,Electronics,500084
1,CA-002,Jane Doe,07-01-2020,11-01-2020,Consumer,West,3,300,45,0.2,Furniture,500081
3,CA-003,ANNA GRAY,10-01-2020,15-01-2020,Corporate,East,5,500,missing,15%,Office Supplies,500002
4,CA-004,Mark Lee,2020-01-12,,Home Office,East,1,N/A,10,5%,Furniture,500001
5,CA-005,mary jane,14-01-2020,17-01-2020,consumer,South,4,400.5,70,N/A,Electronics,500084A

In [ ]:
df['Discount']=df['Discount'].astype(str).str.replace('%',"")
df['Discount']=pd.to_numeric(df['Discount'],errors='coerce')

df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')
df['Ship_Date']=pd.to_datetime(df['Ship_Date'],errors='coerce')


df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')
df['Sales']=pd.to_numeric(df['Sales'],errors='coerce')

In [ ]:
df.isnull().sum()

Order_Id             0
Customer_Name        0
Order_Date          19
Ship_Date           16
Segment              0
Region               0
Quantity             3
Sales                5
Profit               1
Discount             5
Product_Category     0
Postal_Code          0
dtype: int64