<a href="https://colab.research.google.com/github/NagaSaiRamu/Data-Analytics-/blob/main/DataSets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('food.csv')

In [ ]:
df.head()

,order_id,customer_id,restaurant_id,driver_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,city,...,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,order_status,cancellation_reason,customer_rating
0,ORD_000001,CUS_00001,RES_0008,DRV_0075,2025-10-05 15:54:00,2025-10-05,15,Sunday,1,City_C,...,Medium,14,4.4,25,25,29.0,0.0,Completed,NaN,4.6
1,ORD_000002,CUS_00013,RES_0024,DRV_0131,2025-10-01 20:00:00,2025-10-01,20,Wednesday,0,City_A,...,High,44,4.7,12,20,24.0,0.0,Completed,NaN,5.0
2,ORD_000003,CUS_00049,RES_0013,DRV_0087,2025-10-07 18:24:00,2025-10-07,18,Tuesday,0,City_C,...,High,1,5.0,11,63,72.0,1.0,Completed,NaN,3.6
3,ORD_000004,CUS_00007,RES_0001,DRV_0177,2025-10-30 16:54:00,2025-10-30,16,Thursday,0,City_A,...,Low,50,4.3,12,23,31.0,1.0,Completed,NaN,4.1
4,ORD_000005,CUS_00325,RES_0029,DRV_0114,2025-10-15 18:34:00,2025-10-15,18,Wednesday,0,City_B,...,Medium,21,4.0,9,32,42.0,1.0,Completed,NaN,3.9

In [ ]:
df.sample(1)

,order_id,customer_id,restaurant_id,driver_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,city,...,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,order_status,cancellation_reason,customer_rating
32380,ORD_032381,CUS_00154,RES_0115,DRV_0145,2025-10-02 12:00:00,2025-10-02,12,Thursday,0,City_B,...,High,12,4.6,19,84,90.0,1.0,Completed,NaN,4.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 37 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   order_id                             50000 non-null  object
 1   customer_id                          50000 non-null  object
 2   restaurant_id                        50000 non-null  object
 3   driver_id                            50000 non-null  object
 4   order_timestamp                      50000 non-null  object
 5   order_date                           50000 non-null  object
 6   order_hour                           50000 non-null  int64
 7   day_of_week                          50000 non-null  object
 8   is_weekend                           50000 non-null  int64
 9   city                                 50000 non-null  object
 10  delivery_area                        50000 non-null  object
 11  customer_age                         50000 non-null  int64
 12  customer_type                        50000 non-null  object
 13  restaurant_type                      50000 non-null  object
 14  restaurant_primary_category          50000 non-null  object
 15  restaurant_rating                    50000 non-null  float64
 16  items_count                          50000 non-null  int64
 17  subtotal                             50000 non-null  float64
 18  discount_percent                     50000 non-null  int64
 19  tax_amount                           50000 non-null  float64
 20  service_fee                          50000 non-null  float64
 21  delivery_fee                         50000 non-null  float64
 22  order_total                          50000 non-null  float64
 23  payment_method                       50000 non-null  object
 24  tip_amount                           49132 non-null  float64
 25  distance_km                          50000 non-null  float64
 26  weather                              50000 non-null  object
 27  traffic_level                        50000 non-null  object
 28  delivery_partner_experience_months   50000 non-null  int64
 29  delivery_partner_rating              50000 non-null  float64
 30  restaurant_preparation_time_minutes  50000 non-null  int64
 31  estimated_delivery_time_minutes      50000 non-null  int64
 32  actual_delivery_time_minutes         49132 non-null  float64
 33  late_delivery                        49132 non-null  float64
 34  order_status                         50000 non-null  object
 35  cancellation_reason                  868 non-null    object
 36  customer_rating                      49132 non-null  float64
dtypes: float64(12), int64(8), object(17)
memory usage: 14.1+ MB

In [ ]:
df.sample(5)

,order_id,customer_id,restaurant_id,driver_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,city,...,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,order_status,cancellation_reason,customer_rating
7584,ORD_007585,CUS_00047,RES_0152,DRV_0146,2025-10-30 12:26:00,2025-10-30,12,Thursday,0,City_A,...,Medium,53,4.8,15,19,22.0,0.0,Completed,NaN,4.6
28714,ORD_028715,CUS_00217,RES_0027,DRV_0144,2025-10-30 00:32:00,2025-10-30,0,Thursday,0,City_A,...,Low,55,4.4,14,26,21.0,0.0,Completed,NaN,5.0
20868,ORD_020869,CUS_00002,RES_0003,DRV_0019,2025-10-10 11:57:00,2025-10-10,11,Friday,0,City_C,...,Medium,59,5.0,6,20,21.0,0.0,Completed,NaN,4.7
11379,ORD_011380,CUS_00005,RES_0090,DRV_0130,2025-10-06 02:09:00,2025-10-06,2,Monday,0,City_B,...,Low,6,4.5,11,27,29.0,0.0,Completed,NaN,5.0
42005,ORD_042006,CUS_00065,RES_0018,DRV_0133,2025-10-09 20:42:00,2025-10-09,20,Thursday,0,City_B,...,High,29,4.3,9,18,20.0,0.0,Completed,NaN,4.6

In [ ]:
df.describe()

,order_hour,is_weekend,customer_age,restaurant_rating,items_count,subtotal,discount_percent,tax_amount,service_fee,delivery_fee,order_total,tip_amount,distance_km,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,customer_rating
count,50000.000000,50000.00000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,49132.000000,50000.000000,50000.0000,50000.000000,50000.000000,50000.000000,49132.000000,49132.000000,49132.000000
mean,14.465900,0.26712,27.686580,4.207956,2.91002,30.897938,4.495700,4.128796,1.474600,3.075108,38.169501,1.610076,4.730632,29.7332,4.495062,15.549600,30.950580,35.152365,0.365709,4.295946
std,5.231155,0.44246,7.537796,0.450977,2.02907,27.068965,6.430008,3.636275,1.378101,2.299115,31.054669,2.878464,2.780190,17.4052,0.349198,7.360099,12.825519,14.701154,0.481633,0.530947
min,0.000000,0.00000,18.000000,2.800000,1.00000,5.100000,0.000000,0.570000,0.130000,0.000000,4.870000,0.000000,0.800000,1.0000,3.200000,5.000000,8.000000,10.000000,0.000000,1.800000
25%,11.000000,0.00000,21.000000,3.900000,1.00000,13.100000,0.000000,1.730000,0.580000,0.000000,17.430000,0.000000,2.800000,14.0000,4.300000,10.000000,22.000000,25.000000,0.000000,4.000000
50%,14.000000,0.00000,27.000000,4.200000,2.00000,22.825000,0.000000,2.890000,1.040000,3.500000,28.350000,0.000000,4.100000,29.0000,4.500000,14.000000,28.000000,33.000000,0.000000,4.400000
75%,19.000000,1.00000,33.000000,4.600000,4.00000,40.120000,10.000000,5.390000,1.890000,4.500000,48.660000,2.280000,5.900000,44.0000,4.800000,19.000000,37.000000,42.000000,1.000000,4.700000
max,23.000000,1.00000,55.000000,5.000000,10.00000,362.980000,20.000000,50.820000,25.210000,12.000000,443.210000,53.650000,20.000000,60.0000,5.000000,73.000000,128.000000,172.000000,1.000000,5.000000

In [ ]:
df.set_index('order_id')

,customer_id,restaurant_id,driver_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,city,delivery_area,...,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,order_status,cancellation_reason,customer_rating
order_id,,,,,,,,,,,,,,,,,,,,,
ORD_000001,CUS_00001,RES_0008,DRV_0075,2025-10-05 15:54:00,2025-10-05,15,Sunday,1,City_C,City_C_Area_3,...,Medium,14,4.4,25,25,29.0,0.0,Completed,NaN,4.6
ORD_000002,CUS_00013,RES_0024,DRV_0131,2025-10-01 20:00:00,2025-10-01,20,Wednesday,0,City_A,City_A_Area_1,...,High,44,4.7,12,20,24.0,0.0,Completed,NaN,5.0
ORD_000003,CUS_00049,RES_0013,DRV_0087,2025-10-07 18:24:00,2025-10-07,18,Tuesday,0,City_C,City_C_Area_3,...,High,1,5.0,11,63,72.0,1.0,Completed,NaN,3.6
ORD_000004,CUS_00007,RES_0001,DRV_0177,2025-10-30 16:54:00,2025-10-30,16,Thursday,0,City_A,City_A_Area_1,...,Low,50,4.3,12,23,31.0,1.0,Completed,NaN,4.1
ORD_000005,CUS_00325,RES_0029,DRV_0114,2025-10-15 18:34:00,2025-10-15,18,Wednesday,0,City_B,City_B_Area_6,...,Medium,21,4.0,9,32,42.0,1.0,Completed,NaN,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ORD_049996,CUS_00280,RES_0130,DRV_0112,2025-10-25 12:16:00,2025-10-25,12,Saturday,1,City_B,City_B_Area_4,...,Medium,34,5.0,11,19,21.0,0.0,Completed,NaN,4.4
ORD_049997,CUS_00893,RES_0028,DRV_0036,2025-10-05 19:48:00,2025-10-05,19,Sunday,1,City_B,City_B_Area_10,...,High,49,5.0,9,28,29.0,0.0,Completed,NaN,4.8
ORD_049998,CUS_01618,RES_0001,DRV_0071,2025-10-08 12:18:00,2025-10-08,12,Wednesday,0,City_A,City_A_Area_4,...,High,54,4.1,11,18,16.0,0.0,Completed,NaN,4.7
ORD_049999,CUS_00025,RES_0057,DRV_0103,2025-10-20 17:39:00,2025-10-20,17,Monday,0,City_A,City_A_Area_7,...,High,33,4.0,20,17,27.0,1.0,Completed,NaN,3.8
ORD_050000,CUS_00038,RES_0139,DRV_0131,2025-10-13 17:36:00,2025-10-13,17,Monday,0,City_A,City_A_Area_5,...,Low,44,4.7,12,30,40.0,1.0,Completed,NaN,4.5

In [ ]:
df.head()

,order_id,customer_id,restaurant_id,driver_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,city,...,traffic_level,delivery_partner_experience_months,delivery_partner_rating,restaurant_preparation_time_minutes,estimated_delivery_time_minutes,actual_delivery_time_minutes,late_delivery,order_status,cancellation_reason,customer_rating
0,ORD_000001,CUS_00001,RES_0008,DRV_0075,2025-10-05 15:54:00,2025-10-05,15,Sunday,1,City_C,...,Medium,14,4.4,25,25,29.0,0.0,Completed,NaN,4.6
1,ORD_000002,CUS_00013,RES_0024,DRV_0131,2025-10-01 20:00:00,2025-10-01,20,Wednesday,0,City_A,...,High,44,4.7,12,20,24.0,0.0,Completed,NaN,5.0
2,ORD_000003,CUS_00049,RES_0013,DRV_0087,2025-10-07 18:24:00,2025-10-07,18,Tuesday,0,City_C,...,High,1,5.0,11,63,72.0,1.0,Completed,NaN,3.6
3,ORD_000004,CUS_00007,RES_0001,DRV_0177,2025-10-30 16:54:00,2025-10-30,16,Thursday,0,City_A,...,Low,50,4.3,12,23,31.0,1.0,Completed,NaN,4.1
4,ORD_000005,CUS_00325,RES_0029,DRV_0114,2025-10-15 18:34:00,2025-10-15,18,Wednesday,0,City_B,...,Medium,21,4.0,9,32,42.0,1.0,Completed,NaN,3.9